spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/business_service_db
    username: ETA_DBUser
    password: ${DB_PASSWORD}
  rabbitmq:
    host: rabbitmq
    username: service-user
    password: servicepassword

minio:
  endpoint: http://minio:9000
  base:
    path: http://${SERVER_TAILSCALE_IP}:9000/business-service/
